### ISSUE TITLE
[Docs] 신규 입사자 이름 추가 (윤군재)

### ISSUE THREAD

**Issue by gunjae-yoon** [PLAIF-dev/.github#15]
플라잎 메인 페이지에 개발자 개인 정보를 추가합니다.

**Comment by jongwooparkk** [comment]
첫날에 제가 휴가여서 오늘 인사 드립니다~
즐겁고, 활기찬 소프트웨어 팀에 오신걸 환영합니다~

**Comment by leewoojae** [comment]
반갑습니다! 잘 부탁드립니다! 
리눅스.. 모르는거.. 많이.. 찾아뵙겠습니다.. :eyes:
