### ISSUE TITLE
팀 바꾸기 (이지훈)

### ISSUE THREAD

**Issue by BlindedShooter** [PLAIF-dev/.github#62]
저는 이제 모션팀입니다

**Comment by SA-Baitham** [comment]
ML team will miss you~

**Comment by SA-Baitham** [comment]
W
![Screenshot 2024-10-08 104149](https://github.com/user-attachments/assets/689c8089-5a88-4bc6-a47e-7dac3b1fc720)
elcome back to ML team

**Comment by BlindedShooter** [comment]
🤫🤫
